# Generated by Django 5.1.1 on 2024-10-18 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('biografia', models.TextField(verbose_name='Biografía')),
                ('fnacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('estado', models.PositiveIntegerField(verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autores',
                'ordering': ['nombre', 'biografia', 'fnacimiento', 'nacionalidad', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_rol', models.PositiveIntegerField(verbose_name='Rol')),
                ('estado', models.PositiveIntegerField(verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['nombre', 'correo', 'contrasena', 'fecha_creacion', 'fecha_modificacion', 'id_rol', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('fpublicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('id_editorial', models.PositiveIntegerField(verbose_name='Editorial')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('nro_paginas', models.PositiveIntegerField(verbose_name='Número de Páginas')),
                ('idioma', models.PositiveIntegerField(verbose_name='Idioma')),
                ('estado', models.PositiveIntegerField(verbose_name='Estado')),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbiblioteca.autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libros',
                'ordering': ['titulo', 'id_autor', 'fpublicacion', 'id_editorial', 'stock', 'nro_paginas', 'idioma', 'estado'],
            },
        ),
    ]
